version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${S3_REGION}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
      CORS_ORIGINS: ${CORS_ORIGINS}
      PORT: ${API_PORT}
      OPENAPI_PATH: infra/openapi/openapi.yaml
      PRISMA_SCHEMA_PATH: infra/prisma/schema.prisma
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./packages/api:/usr/src/app
      - ./infra/openapi:/usr/src/app/infra/openapi
      - ./infra/prisma:/usr/src/app/infra/prisma
    command: pnpm run start:docker

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: http://api:3000
    ports:
      - "${WEB_PORT}:5173"
    volumes:
      - ./packages/web:/usr/src/app
    command: pnpm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres-data:
  minio-data:
